before:
  hooks:
    - go mod download
builds:
- binary: packagecloud
  main: ./cmd/packagecloud/main.go
  env:
    - CGO_ENABLED=0
  targets:
    - darwin_amd64
    - linux_amd64
    - linux_arm64
    - windows_amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
